# Generated by Django 4.1.1 on 2022-09-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(choices=[('500g', '500g'), ('1kg', '1kg'), ('2.5kg', '2.5kg'), ('5kg', '5kg')], default='500g', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
