# Generated by Django 4.1.1 on 2022-09-18 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductName',
        ),
    ]
