# Generated by Django 4.1.1 on 2022-09-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_product_name_delete_productname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=150, null=True, unique=True),
        ),
    ]
