# Generated by Django 3.1.2 on 2021-05-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zip_code',
            new_name='zipcode',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='ecommerce/image-4.jpg', upload_to=''),
        ),
    ]
