# Generated by Django 3.1.2 on 2021-06-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_completedtransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtransaction',
            name='reference_number',
        ),
        migrations.AddField(
            model_name='completedtransaction',
            name='tracking',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
