# Generated by Django 3.1.2 on 2021-06-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_remove_completedtransaction_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtransaction',
            name='tracking_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
