# Generated by Django 3.1.2 on 2021-06-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_auto_20210617_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtransaction',
            name='tracking_id',
        ),
    ]
