# Generated by Django 3.1.2 on 2021-06-17 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_remove_completedtransaction_tracking_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompletedTransaction',
        ),
    ]
