# Generated by Django 3.1.2 on 2021-06-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_delete_completedtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
