# Generated by Django 3.1.2 on 2021-06-17 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_auto_20210617_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtransaction',
            name='tracking_id',
        ),
        migrations.AddField(
            model_name='completedtransaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.customer'),
        ),
    ]
