# Generated by Django 3.1.2 on 2021-06-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_auto_20210617_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtransaction',
            name='message',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='completedtransaction',
            name='tracking_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
