# Generated by Django 3.1.2 on 2021-06-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_auto_20210617_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='other_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
