# Generated by Django 3.1.2 on 2021-06-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_auto_20210620_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='other_image_1',
            field=models.ImageField(default='ecommerce/image-4.jpg', upload_to=''),
        ),
    ]
