# Generated by Django 3.1.2 on 2021-07-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0024_auto_20210620_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='other_image_1',
            field=models.ImageField(default='chin-chin.jpg', upload_to=''),
        ),
    ]
