# Generated by Django 3.1.2 on 2021-08-06 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0027_auto_20210728_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtransaction',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.customer'),
        ),
    ]
