# Generated by Django 4.1.1 on 2022-09-08 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
